version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build_docs:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: echo "placeholder"

workflows:
  main:
    jobs:
      - build_docs
