version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build_docs:
    steps:
      - checkout
      - run:
          command: echo "placeholder"
    
workflows:
  main:
    jobs:
      - build_docs
